blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/aygp-dr/verbiste-wasm/blob/main/README.md
    about: Check out the project documentation before opening an issue